apiVersion: v1
kind: Service
metadata:
  name: minecraft
  labels:
    name: minecraft
spec:
  type: ClusterIP
  ports:
  - name: tcp-25565
    port: 25565
    targetPort: 25565
  - name: tcp-25575
    port: 25575
    targetPort: 25575
  selector:
    name: minecraft-app
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: minecraft-app-deploy
  labels:
    name: minecraft-app
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: minecraft-app
    spec:
      containers:
      - image: openhack/minecraft-server:1.0
        name: minecraft-app-cntnr
        resources:
          requests:
            cpu: "20m"
            memory: "55M"
        ports:
        - containerPort:  27017
          name:  heroes-db
        volumeMounts:
        - mountPath: /data
          name: data
        imagePullPolicy: Always
      volumes:
        - name: data
          emptyDir: {}
      restartPolicy: Always
