apiVersion: v1
kind: Service
metadata:
  name: minecraft-ext
  labels:
    name: minecraft-ext
spec:
  type: LoadBalancer
  ports:
  - name: ext-25565
    port: 25565
    targetPort: 25565
  - name: ext-25575
    port: 25575
    targetPort: 25575
  selector:
    name: minecraft-app
